#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("app1.Droid.Resource", IsApplication=true)]

namespace app1.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_guide_into = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_login_password = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_login_user = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IMG_2365 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int register_code = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int register_invite = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int register_pass1 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int CreateAccountButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int LoginButton = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int author = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int bookName = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int book_category = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int buyBookButton = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ch_borrow = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ch_buy = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int confirmsell = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int createAccountSubmitButton = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int et_login_mail = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int et_login_psd = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int et_login_usr = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int login = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int publishing_house = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int rl_pay_category = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int sellBooksButton = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int tv_book_category_info = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int choose = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int choose_book = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int regist = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int sell_books = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
